// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CineForge AI - Transforme palavras em vídeos épicos",
  description: "Plataforma revolucionária de criação de vídeos automáticos e profissionais com IA. Gere vídeos para YouTube, TikTok e Reels em minutos.",
  keywords: "criação de vídeos, IA, inteligência artificial, vídeos automáticos, YouTube, TikTok, Reels",
  openGraph: {
    title: "CineForge AI - Transforme palavras em vídeos épicos",
    description: "Crie vídeos profissionais com IA em minutos",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="dark">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body className={`${inter.variable} font-sans antialiased bg-[#121212] text-white`}>
        {children}
      </body>
    </html>
  );
}
